Repository CS2103-AY1819S1-F11-3/main, pull requests merged in 2018-10, with the labels that each got.

#76 Add batch complete features via label
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/logic/parser/CompleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedTaskManager.java
  src/main/java/seedu/address/model/task/LabelMatchesKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CompleteCommandTest.java
  src/test/java/seedu/address/logic/parser/CompleteCommandParserTest.java
  src/test/java/seedu/address/model/VersionedTaskManagerTest.java
  src/test/java/seedu/address/model/task/LabelMatchesKeywordPredicateTest.java
Labels: type.Task

#78 Achievements field
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/achievement/AchievementRecord.java
  src/main/java/seedu/address/model/achievement/Level.java
  src/main/java/seedu/address/model/achievement/Xp.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedAchievementRecord.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/storage/XmlSerializableTaskManager.java
  src/test/data/XmlSerializableTaskManagerTest/duplicateTaskTaskManager.xml
  src/test/data/XmlSerializableTaskManagerTest/invalidTaskManager.xml
  src/test/data/XmlSerializableTaskManagerTest/typicalTasksTaskManager.xml
  src/test/data/XmlTaskManagerStorageTest/invalidAndValidTaskTaskManager.xml
  src/test/data/XmlTaskManagerStorageTest/invalidTaskManager.xml
  src/test/data/XmlUtilTest/validTaskManager.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CompleteCommandTest.java
  src/test/java/seedu/address/model/TaskManagerTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
Labels: type.Task

#90 Add Coveralls for Repo
  README.adoc
Labels: priority.Low, type.Task

#91 Add coveralls again
  README.adoc
Labels: priority.Low, type.Task

#93 Update User Guide for Complete Command
  docs/UserGuide.adoc
Labels: priority.High

#84 Dependency validity
  src/main/java/seedu/address/logic/commands/DependencyCommand.java
  src/main/java/seedu/address/model/DependencyGraph.java
  src/main/java/seedu/address/model/task/exceptions/GraphCycleException.java
  src/test/java/seedu/address/logic/commands/DependencyCommandTest.java
  src/test/java/seedu/address/model/task/DependencyGraphTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High, type.Task

#103 Fix typo in getMatchingLevel
  src/main/java/seedu/address/model/achievement/AchievementRecord.java
Labels: type.Bug

#95 Add "today" filter for list
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/task/DueDateIsBeforeTodayPredicate.java
  src/main/java/seedu/address/model/util/DateFormatUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.Medium, type.Enhancement

#88 Add Documentation on Batch Completion via Label
  docs/DeveloperGuide.adoc
  docs/diagrams/CompleteViaLabelOnFail.psd
  docs/diagrams/CompleteViaLabelOnSuccess.psd
  docs/images/CompleteViaLabelOnFail.png
  docs/images/CompleteViaLabelOnSuccess.png
Labels: priority.Medium, status.Ongoing

#114 Add documentation for Dependency Command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DependencyCommandSequenceDiagram.pptx
  docs/images/DependencyCommandSequenceDiagram.png
Labels: priority.Medium

#113 Undo/Redo Diagrams: Rename classes
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
Labels: type.Task

#121 Add achievement mechanism to DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/AchievementDiagrams.pptx
  docs/images/AchievementActivity.png
  docs/images/AchievementModel.png
  docs/images/AchievementSequence1.png
  docs/images/AchievementSequence2.png
Labels: type.Task

#125 Provide points reporting for CompleteCommand's message on success
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/achievement/AchievementRecord.java
  src/main/java/seedu/address/model/achievement/Xp.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CompleteCommandTest.java
Labels: priority.High, type.Task

#133 Add UI component for achievement field
  config.json
  src/main/java/seedu/address/commons/events/model/AchievementsUpdatedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/storage/XmlSerializableTaskManager.java
  src/main/java/seedu/address/ui/AchievementPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AchievementPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/AchievementPanelHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/TaskManagerTest.java
  src/test/java/seedu/address/ui/AchievementPanelTest.java
Labels: priority.Medium, type.Task

#142 Enhance CompleteCommand: Add reporting feature on level up
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/achievement/Level.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#141 Topological Sort removes completed tasks before performing sort
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DependencyCommand.java
  src/main/java/seedu/address/model/DependencyGraph.java
  src/main/java/seedu/address/model/task/Dependency.java
  src/test/java/seedu/address/logic/commands/DependencyCommandTest.java
  src/test/java/seedu/address/model/task/DependencyGraphTest.java
Labels: type.Task

#140 Add time based achievements to the achievement mechanism
  src/main/java/seedu/address/logic/commands/AchievementsCommand.java
  src/main/java/seedu/address/logic/parser/AchievementsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/achievement/AchievementRecord.java
  src/main/java/seedu/address/model/achievement/Level.java
  src/main/java/seedu/address/storage/XmlAdaptedAchievementRecord.java
  src/main/java/seedu/address/ui/AchievementPanel.java
  src/main/resources/view/AchievementPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/XmlSerializableTaskManagerTest/duplicateTaskTaskManager.xml
  src/test/data/XmlSerializableTaskManagerTest/invalidTaskManager.xml
  src/test/data/XmlSerializableTaskManagerTest/typicalTasksTaskManager.xml
  src/test/data/XmlTaskManagerStorageTest/invalidAndValidTaskTaskManager.xml
  src/test/data/XmlTaskManagerStorageTest/invalidTaskManager.xml
  src/test/data/XmlUtilTest/validTaskManager.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/AchievementRecordBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
  src/test/java/seedu/address/ui/AchievementPanelTest.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
Labels: type.Task

#146 Refactor complete command to two separate classes
  src/main/java/seedu/address/logic/commands/CompleteCommand.java
  src/main/java/seedu/address/logic/commands/CompleteIndexCommand.java
  src/main/java/seedu/address/logic/commands/CompleteLabelCommand.java
  src/main/java/seedu/address/logic/parser/CompleteCommandParser.java
  src/test/java/seedu/address/logic/commands/CompleteIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/CompleteLabelCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CompleteCommandParserTest.java
Labels: priority.Medium, type.Task

#144 Flag tasks as overdue
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AchievementsCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CompleteIndexCommand.java
  src/main/java/seedu/address/logic/commands/CompleteLabelCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DependencyCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/DependencyGraph.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/game/GameManager.java
  src/main/java/seedu/address/model/task/DueDate.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CompleteIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/CompleteLabelCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DependencyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/parser/TaskManagerParserTest.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/TaskManagerSystemTest.java
Labels: priority.High, type.Task

#148 ListCommand: Add filters for end of week/month
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/task/DueDateIsBeforeEndOfMonthPredicate.java
  src/main/java/seedu/address/model/task/DueDateIsBeforeEndOfWeekPredicate.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: priority.Medium, type.Enhancement
