Repository CS2103-AY1819S1-F11-3/main, pull requests merged in 2018-11, with the labels that each got.

#150 Update user guide for v1.3
  docs/UserGuide.adoc
  docs/images/ActualUi.png
Labels: type.Task

#151 Complete label command case insensitive match
  src/main/java/seedu/address/model/task/LabelMatchesKeywordPredicate.java
  src/test/java/seedu/address/model/task/LabelMatchesKeywordPredicateTest.java
Labels: priority.High, type.Enhancement, type.Task

#158 Update achievement mechanism dev guide
  docs/DeveloperGuide.adoc
  docs/diagrams/AchievementDiagrams.pptx
  docs/images/AchievementActivity.png
  docs/images/AchievementModel.png
  docs/images/AchievementSequence1.png
  docs/images/AchievementSequence2.png
Labels: type.Task

#166 Change default game mode
  src/main/java/seedu/address/model/game/GameManager.java
Labels: priority.Medium

#165 Add CompleteCommandParserTest test
  src/test/java/seedu/address/logic/parser/CompleteCommandParserTest.java
Labels: priority.High, type.Task

#163 Update docs for Command Component
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CommandComponentClassDiagram.pptx
  docs/images/CommandComponentClassDiagram.png
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/TaskCard.java
Labels: priority.High, type.Task

#154 List blocking tasks
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/task/Dependency.java
  src/main/java/seedu/address/model/task/IsNotBlockedPredicate.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High, type.Enhancement

#172 Update Readme
  README.adoc
Labels: priority.Low

#188 Fix edit command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug

#206 Add tests for AchievementRecord, XmlAdaptedAchievementRecord and AchievementPanel
  src/main/java/seedu/address/model/achievement/AchievementRecord.java
  src/main/java/seedu/address/model/achievement/exceptions/CumulativeAchievementsMismatchException.java
  src/main/java/seedu/address/model/achievement/exceptions/DateBreakPointsMismatchException.java
  src/main/java/seedu/address/model/achievement/exceptions/XpLevelMismatchException.java
  src/main/java/seedu/address/storage/XmlAdaptedAchievementRecord.java
  src/main/java/seedu/address/ui/AchievementPanel.java
  src/main/resources/view/AchievementPanel.fxml
  src/test/java/guitests/guihandles/AchievementPanelHandle.java
  src/test/java/seedu/address/model/achievement/AchievementRecordTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAchievementRecordTest.java
  src/test/java/seedu/address/testutil/AchievementRecordBuilder.java
  src/test/java/seedu/address/testutil/XmlAchievementRecordBuilder.java
  src/test/java/seedu/address/ui/AchievementPanelTest.java
Labels: type.Task

#212 Amend Date Parser to solve date parsing bug
  src/main/java/seedu/address/model/task/DueDate.java
  src/main/java/seedu/address/model/util/DateFormatUtil.java
Labels: type.Bug

#213 Add achievements command and parser test
  src/test/java/seedu/address/logic/commands/AchievementsCommandTest.java
  src/test/java/seedu/address/logic/parser/AchievementsCommandParserTest.java
Labels: type.Task

#221 Add First Draft for PPP Jeff
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/unsatisfiedpopcorn.adoc
Labels: type.Task

#219 Add functionalities to display time until due date
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ShowTopologicalOrderCommand.java
  src/main/java/seedu/address/model/task/DueDate.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/guitests/guihandles/TaskCardHandle.java
Labels: type.Task

#222 Fix AddCommands and ListCommands documentation
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: priority.Medium

#233 Update PPP
  docs/team/unsatisfiedpopcorn.adoc
Labels: priority.Medium

#223 Add feature to display time wrt dependency
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/DependencyGraph.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/task/DueDate.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/TaskManagerTest.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
Labels: priority.High

#241 Add UI to view a single Task
  src/main/java/seedu/address/model/task/IsNotBlockedPredicate.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/java/seedu/address/ui/TaskViewPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TaskViewPanel.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/TaskCardHandle.java
  src/test/java/guitests/guihandles/TaskViewPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
  src/test/java/seedu/address/ui/TaskViewPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/TaskManagerSystemTest.java
Labels: priority.High

#238 Prevent achievement info from getting reset on clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: type.Bug

#254 Fix priority value overflow bug
  src/main/java/seedu/address/model/game/PriorityMode.java
  src/main/java/seedu/address/model/task/PriorityValue.java
  src/test/java/seedu/address/model/game/GameModeTest.java
  src/test/java/seedu/address/model/task/PriorityValueTest.java
Labels: type.Bug

#265 Refactoring achievement codes
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/achievement/AchievementRecord.java
  src/main/java/seedu/address/model/achievement/Xp.java
  src/main/java/seedu/address/storage/XmlAdaptedAchievementRecord.java
Labels: type.Task

#263 Truncate Task labels
  src/main/java/seedu/address/model/task/DueDate.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskViewPanel.java
Labels: priority.Low

#262 Fix UI Layout
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskViewPanel.fxml
Labels: severity.Medium

#268 Add Regression Tests for CompleteCommandParser
  src/test/java/seedu/address/logic/parser/CompleteCommandParserTest.java
Labels: priority.Medium, type.Task

#273 Refactor year from 2018 to 2019
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/XmlSerializableTaskManagerTest/duplicateTaskTaskManager.xml
  src/test/data/XmlSerializableTaskManagerTest/invalidTaskManager.xml
  src/test/data/XmlSerializableTaskManagerTest/typicalTasksTaskManager.xml
  src/test/data/XmlTaskManagerStorageTest/invalidAndValidTaskTaskManager.xml
  src/test/data/XmlTaskManagerStorageTest/invalidTaskManager.xml
  src/test/data/XmlUtilTest/missingTaskField.xml
  src/test/data/XmlUtilTest/validTask.xml
  src/test/data/XmlUtilTest/validTaskManager.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/game/DecreasingModeTest.java
  src/test/java/seedu/address/model/task/DueDateTest.java
  src/test/java/seedu/address/model/util/DateFormatUtilTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
Labels: type.Task
